---
- name: nsd_enable
  ansible.builtin.systemd:
    name: nsd.service
    enabled: yes
  become: yes

- name: nsd_restart
  ansible.builtin.systemd:
    name: nsd.service
    state: restarted
  become: yes
