version: "3.9"
services:
  nginx4.1:
    image: nginx:latest
    container_name: nginx4.1
    hostname: nginx4.1
    volumes: [ ./nginx4.1.html:/usr/share/nginx/html/index.html ]
    networks:
      proxy145: { ipv4_address: 10.145.4.221 }

networks:
  proxy145:
    name: proxy145
    external: true
