version: "3.9"
services:
  testpage-it:
    image: nginx:latest
    container_name: testpage-it
    hostname: testpage-it
    volumes: [ ./nginx4.1.html:/usr/share/nginx/html/index.html ]
    networks:
      proxy145: { ipv4_address: 10.145.4.221 }

networks:
  proxy145:
    name: proxy145
    external: true
