version: "3.9"
services:
  testpage-en:
    image: nginx:latest
    container_name: testpage-en
    hostname: testpage-en
    volumes: [ ./nginx4.0.html:/usr/share/nginx/html/index.html ]
    networks:
      proxy145: { ipv4_address: 10.145.4.220 }

networks:
  proxy145:
    name: proxy145
    external: true
