version: "3.9"
services:
  nginx4.0:
    image: nginx:latest
    container_name: nginx4.0
    hostname: nginx4.0
    volumes: [ ./nginx4.0.html:/usr/share/nginx/html/index.html ]
    networks:
      proxy145: { ipv4_address: 10.145.4.220 }

networks:
  proxy145:
    name: proxy145
    external: true
