---
- name: node exporter をインストールする
  ansible.builtin.apt:
    name: prometheus-blackbox-exporter
    state: present
  become: yes
  notify: blackbox_exporter_enable

- name: /etc/prometheus/blackbox.yml を配付する
  ansible.builtin.copy:
    src: ./etc/prometheus/blackbox.yml
    dest: /etc/prometheus/blackbox.yml
  become: yes
  notify: blackbox_exporter_restart



#- name: /etc/prometheus/prometheus.yml を配付する
#  #ansible.builtin.template:
#  #  src: ./etc/prometheus/prometheus.yml.j2
#  ansible.builtin.copy:
#    src: ./etc/prometheus/prometheus.yml
#    dest: /etc/prometheus/prometheus.yml
#  become: yes
#  notify: prometheus_restart
#
#- name: /etc/prometheus/targets.d を配付する
#  block:
#  - name: ディレクトリ作成
#    ansible.builtin.file:
#      path: /etc/prometheus/targets.d
#      state: directory
#  - name: ファイルの配付
#    #ansible.builtin.template:
#    #  src: ./etc/prometheus/targets.d/{{ item }}.j2
#    ansible.builtin.copy:
#      src: ./etc/prometheus/targets.d/{{ item }}
#      dest: /etc/prometheus/targets.d/{{ item }}
#    loop:
#    - proxmox.yml
#    - raspberry.yml
#    notify: prometheus_restart
#  become: yes
#
#- name: /etc/prometheus/scrapes.d を配付する
#  block:
#  - name: ディレクトリ作成
#    ansible.builtin.file:
#      path: /etc/prometheus/scrapes.d
#      state: directory
#  - name: ファイルの配付
#    #ansible.builtin.template:
#    #  src: ./etc/prometheus/scrapes.d/{{ item }}.j2
#    ansible.builtin.copy:
#      src: ./etc/prometheus/scrapes.d/{{ item }}
#      dest: /etc/prometheus/scrapes.d/{{ item }}
#    loop:
#    - proxmox.yml
#    - raspberry.yml
#    notify: prometheus_restart
#  become: yes
#
#- name: /etc/prometheus/rules.d を配付する
#  block:
#  - name: ディレクトリ作成
#    ansible.builtin.file:
#      path: /etc/prometheus/rules.d
#      state: directory
#  - name: ファイルの配付
#    ansible.builtin.copy:
#      src: ./etc/prometheus/rules.d/{{ item }}
#      dest: /etc/prometheus/rules.d/{{ item }}
#    loop:
#    - alert-rules.yml
#    notify: prometheus_restart
#  become: yes
  

