---
- name: unbound をインストールする
  ansible.builtin.apt:
    name: unbound
    state: present
  become: yes
  notify: unbound_enable

- name: /etc/unbound/unbound.conf を配付する
  ansible.builtin.template:
    src: ./etc/unbound/unbound.conf.j2
    dest: /etc/unbound/unbound.conf
  become: yes
  notify: unbound_restart
