version: "3.9"
services:
  nginx3.1:
    image: nginx:latest
    container_name: nginx3.1
    hostname: nginx3.1
    volumes: [ ./nginx3.1.html:/usr/share/nginx/html/index.html ]
    networks:
      proxy145: { ipv4_address: 10.145.3.221 }

networks:
  proxy145:
    name: proxy145
    external: true
