version: "3.9"
services:
  testpage-it-3:
    image: nginx:latest
    container_name: testpage-it-3
    hostname: testpage-it-3
    volumes: [ ./nginx3.1.html:/usr/share/nginx/html/index.html ]
    networks:
      overlay12: { ipv4_address: 10.28.12.221 }

networks:
  overlay12:
    name: overlay12
    external: true
