version: "3.9"
services:
  testpage-en-3:
    image: nginx:latest
    container_name: testpage-en-3
    hostname: testpage-en-3
    volumes: [ ./nginx3.0.html:/usr/share/nginx/html/index.html ]
    networks:
      overlay12: { ipv4_address: 10.28.12.220 }

networks:
  overlay12:
    name: overlay12
    external: true
